config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :issues do
    resources :narratives, only: [:index, :show]
  end

  resources :narratives, only: [:new, :create, :edit, :update, :destroy]

root 'static_pages#home'

end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id         :integer          not null, primary key
#  topic      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  image_url  :string
#

class Issue < ActiveRecord::Base
  has_many :narratives
  has_many :users, :through => :narratives
  accepts_nested_attributes_for :narratives
end

app/models/narrative.rb
# == Schema Information
#
# Table name: narratives
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  text        :string
#  result      :text
#  people      :integer
#  location    :integer
#  templates   :string
#  image_url   :string
#  issue_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  topic       :string
#

class Narrative < ActiveRecord::Base
  belongs_to :issue
  validates_associated :issue
  has_one :user
  accepts_nested_attributes_for :issue

  validates :title, length: { maximum: 50, too_long: "%{count} characters is the maximum allowed" }
  validates :description, length: { maximum: 200, too_long: "%{count} characters is the maximum allowed" }
  validates :title, length: { maximum: 200, too_long: "%{count} characters is the maximum allowed" }
  validates :location, length: { maximum: 5, too_long: "%{count} characters is the maximum allowed" }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :narratives
  has_many :issues, :through => :narratives      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  
  def index
    @issues = Issue.all
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new
    if @issue.save
      redirect_to @issue
    else
      render 'new'
    end
  end

  def update
    @issue = Issue.find(params[:id])
      if @issue.update(issue_params)
        redirect_to issue_path
      else
        render 'edit'
      end
  end

  def show
end

private

def issue_params
  params.require(:issue).permit(:topic, :issue_image)
end

end

app/controllers/narratives_controller.rb
class NarrativesController < ApplicationController

  before_action :authenticate_user!

# under issue
  def index
    @issue = Issue.find(params[:issue_id])
    @narratives = @issue.narratives
  end

  def show
      @issue = Issue.find(params[:issue_id])
      @narrative = Narrative.find(params[:id])
  end

# not under issue
  def new
    @narrative = Narrative.new
  end

  def create
    @narrative = Narrative.create(narrative_params)
    if @narrative.save

      redirect_to issue_narratives_path(@narrative.issue)
    else
      render 'new'
    end
  end

  def update
    @issue = Issue.find(params[:topic])
    @narrative = @issue.narrative.update(narrative_params)
  end

  def destroy
    @narrative = Narrative.find(params[:id])
    if @narrative.destroy
      redirect_to issue_narratives_path(@narrative.issue)
    else
      "This story no longer exists"
    end
  end


private

  def narrative_params
    params.require(:narrative).permit(:title, :description, :text, :result, :people, :location, :templates, :image_url, :issue_id)
  end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
      @issues = Issue.all
      @narratives= Narrative.all
  end

  def home
      @issues = Issue.all
      @narratives= Narrative.all
  end

  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/narratives_helper.rb
module NarrativesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/issues/_form.html.erb
<h1> Submit a Topic Suggestion </h1>
<div class="panel-body">
  <%= simple_form_for @issue do |f| %>
    <%= f.input :topic, label: false, input_html: {placeholder: "Name"}%>
    <%= f.input :image_url, label: false, input_html: {placeholder: "Picture"} %>
    <%= f.submit "Submit".html_safe, class: "btn btn-lg btn-danger"%>
  <% end %>
  </div>
</div>

app/views/issues/_issue_fields.html.erb
<%= simple_form_for @issue do |f| %>
  <%= f.input :topic, label: false, input_html: {placeholder: "Name"}%>
<% end %>

app/views/issues/index.html.erb
<section id="portfolio" class="bg-light-gray">
  <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Sustainability Resources</h2>
                <h3 class="section-subheading text-muted">Environmental Topics</h3>
                <background: url("http://www.trackur.com/wp-content/uploads/2013/02/beyoncesuperbowl.jpg")no-repeat bottom center scroll>;
            </div>
        </div>


      <% @issues.each do |issue| %>
      <div class="row">
            <div class="col-md-4 col-sm-6 portfolio-item">
                    <div class="portfolio-hover">
                        <div class="portfolio-hover-content">
                            <%= image_tag(issue.image_url, :class => "img-responsive") %>
                        </div>
                    </div>
                <div class="portfolio-caption">
                    <h4>  <%= issue.topic %> </h4>
                        <p class="text-muted"> <%=link_to 'Stories', issue_narratives_path(issue) %></p>
                </div>
            </div>
            <% end %>

      </div>
      </div>
</section>

app/views/issues/new.html.erb
<%= render 'form' %>

app/views/layouts/_main_nav.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <!-- <a class="navbar-brand page-scroll" href="#page-top">
                <i class="fa fa-play-circle"></i>  <span class="light">Start</span> Bootstrap
            </a> -->
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <%= link_to "Sustainability Issues", issues_path %>
                </li>

                <li>
                    <%= link_to "Sign Up", new_user_registration_path %>
                </li>

                <li>
                    <%= link_to "Log Out", destroy_user_session_path %>
                </li>
                <li>

                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<html>
<head>
  <title>MySustainabilityApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/main_nav' %>

  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/narratives/_form.html.erb
<div class="panel-body">
  <%= simple_form_for (@narrative) do |f| %>
    <%= f.input :title, label: false, input_html: {placeholder: "Title"}%>
    <%= f.association :issue, label_method: :issue_topic, :include_blank => false, :label_method => lambda { |issue| "#{issue.topic}" } %>
    <%= f.input :description, label: false, as: :text, input_html: {placeholder: "Description"} %>
  <%= f.input :result, label: false, as: :text, input_html: {placeholder: "Result"} %>
    <%= f.input :people, label: false, as: :integer, input_html: {placeholder: "Number of People Impacted"} %>
  <%= f.input :location, label: false, as: :integer, input_html: {placeholder: "Location (Zip Code)"} %>
  <%= f.input :templates, label: false, as: :string, input_html: {placeholder: "Templates"} %>
    <%= f.input :image_url, label: false, input_html: {placeholder: "Image"} %>
    <%= f.submit "Submit".html_safe, class: "btn btn-lg btn-danger"%>
  <% end %>
</div>

app/views/narratives/index.html.erb
<section id="portfolio" class="bg-light-gray">
  <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Narratives</h2>
                <h3 class="section-subheading text-muted"> Resources at your fingertips</h3>

            </div>
        </div>
  </div>

<% @issue.narratives.each do |narrative| %>
<div class="row">
      <div class="col-md-4 col-sm-6 portfolio-item">
              <div class="portfolio-hover">
                  <div class="portfolio-hover-content">

                      <%= image_tag(narrative.image_url, :class => "img-responsive") %>
                  </div>
              </div>
          <div class="portfolio-caption">
            <tr>
              <td class="col-md-2"> </td>
              <h4>  <%= link_to narrative.title, issue_narrative_path(narrative.issue, narrative) %> </h4>
    </tr>
    </div>
</div>
</div>
<% end %>
<%=link_to "Contribute Your Story", new_narrative_path, class: 'btn btn-default btn-xs'%>
<%=link_to "Go Back To Issue Topic", issues_path, class: 'btn btn-default btn-xs'%>

app/views/narratives/new.html.erb
<div class= "panel panel-default">
<div class="panel-heading">
  <h1> Submit your story </h1>
</div>

<%= render 'form' %>

app/views/narratives/show.html.erb
<div class="row-fluid">
  <div class="panel panel-default">
  <div class="col-md-30">
  </div>
  <div class="col-md-30">
    <div class="panel panel-default">

      <div class="panel-heading">
<%= @narrative.title%>

      </div>
    </div>
  </div>

<div class="body">
        <h4>  Description: <%= @narrative.description %> </h4>
        <h4>  Result: <%= @narrative.result %> </h4>
        <h4>  Number of People Impacted: <%= @narrative.people %> </h4>
        <h4>  Location: <%= @narrative.location %> </h4>
        <h4>  Templates: <%= @narrative.templates %> </h4>
  </div>
      <%= link_to 'Delete', @narrative, method: :delete, data: {confirm: "Are you sure you want to delete?"}, class: 'btn btn-xs btn-danger' %>
      <%=link_to "Go Back To  Narratives", issue_narratives_path(@issue), class: 'btn btn-default btn-xs'%>

    </div>

app/views/static_pages/home.html.erb
<html lang="en">


<body id="page-top" class="index">

  <body id="page-top" class="index">

      <!-- Navigation -->
      <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header page-scroll">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand page-scroll" href="#page-top">Sustainability in the Workplace</a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-left">
                      <li class="hidden">
                          <a href="#page-top"></a>
                      </li>
                      <li>
                          <a class="page-scroll" href="#portfolio">Take Action</a>
                      </li>
                      <li>
                          <a class="page-scroll" href="#services">Services</a>
                      </li>
                      <li>
                          <a class="page-scroll" href="#about">About</a>
                      </li>
                      <li>
                          <a class="page-scroll" href="#contact">Contact</a>
                      </li>
                  </ul>
              </div>
              <!-- /.navbar-collapse -->
          </div>
          <!-- /.container-fluid -->
      </nav>


    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">Sustainability Initiatives at your fingertips</div>
                <div class="intro-heading">Take Action!</div>
                <a href="#portfolio" class="page-scroll btn btn-xl">Tell Me More</a>
            </div>
        </div>

    </header>



    <!-- Portfolio Grid Section -->

    <%= render template: "issues/index" %>

  <!-- Services Section -->
  <section id="services">
      <div class="container">
          <div class="row">
              <div class="col-lg-12 text-center">
                  <h2 class="section-heading">Services</h2>
                  <h3 class="section-subheading text-muted">Happy to Assist.</h3>
              </div>
          </div>
          <div class="row text-center">
              <div class="col-md-4">
                  <span class="fa-stack fa-4x">
                      <i class="fa fa-circle fa-stack-2x text-primary"></i>
                      <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                  </span>
                  <h4 class="service-heading">Training and Education</h4>
                  <p class="text-muted">Ideas that stick</p>
              </div>
              <div class="col-md-4">
                  <span class="fa-stack fa-4x">
                      <i class="fa fa-circle fa-stack-2x text-primary"></i>
                      <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                  </span>
                  <h4 class="service-heading">Change Management</h4>
                  <p class="text-muted">Change without the chaos</p>
              </div>
              <div class="col-md-4">
                  <span class="fa-stack fa-4x">
                      <i class="fa fa-circle fa-stack-2x text-primary"></i>
                      <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                  </span>
                  <h4 class="service-heading">Process Improvement</h4>
                  <p class="text-muted">Lean Six Sigma Triple Bottom Line Integration</p>
              </div>
          </div>
      </div>
  </section>

    <!-- About Section -->
    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">About</h2>
                    <h3 class="section-subheading text-muted"> Sustainability in the Workplace.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="timeline">
                        <li>
                            <div class="timeline-image">
                                <img url('climate_change.jpg'), class="img-circle img-responsive" alt="">

                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>Climate Change is a serious problem</h4>
                                    <p class="text-muted">Intensified natural disasters, increased pollution, glaciers dissolution, greenhouse gas emissions, waste landfill, and the list goes. There are so many climate change problems that often it feels overwhelming -- feels as if the problem is too big to solve. Here, we are focused on starting small, always one step forward towards a better, brighter and more sustainable world for our future generation. We focus on typical environmental problems at the workplace and provide techniques and resources for everyoen to use to implement change at their workplace. </p>
                                </div>
                                <div class="timeline-body">
                                    <h4>Mission</h4>
                                    <p class="text-muted">Our mission is to inspire sustainability action and provide resources to help create a more sustainable workplace</p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>




    <!-- Contact Section -->
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Contact Us</h2>
                    <h3 class="section-subheading text-muted">For questions or additional information, please send us a message! </h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <form name="sentMessage" id="contactForm" novalidate>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Your Name *" id="name" required data-validation-required-message="Please enter your name.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number.">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <textarea class="form-control" placeholder="Your Message *" id="message" required data-validation-required-message="Please enter a message."></textarea>
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <div id="success"></div>
                                <button type="submit" class="btn btn-xl">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Connie Horng 2015</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="https://www.linkedin.com/pub/connie-horng/3/662/626"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>





</body>

</html>